export const CREATE_SOCIETY_REQUEST = "CREATE_SOCIETY_REQUEST";
export const CREATE_SOCIETY_SUCCESS = "CREATE_SOCIETY_SUCCESS";
export const CREATE_SOCIETY_FAIL = "CREATE_SOCIETY_FAIL"

export const GET_SOCIETY_REQUEST="GET_SOCIETY_REQUEST"
export const GET_SOCIETY_SUCCESS="GET_SOCIETY_SUCCESS"
export const GET_SOCIETY_FAIL="GET_SOCIETY_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"